version: '3'
services:
  mysql:
    container_name: mysql-isucon
    image: mysql
    environment:
      MYSQL_DATABASE: isucari
      MYSQL_USER: isucari
      MYSQL_PASSWORD: isucari
      MYSQL_TCP_PORT: 13306
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      LANG: C.UTF-8
    ports:
      - "13306:13306"
    expose:
      - "13306"
    network_mode: "host"

  isucari-go:
    container_name: isucari-go
    build: ./webapp/go/
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 13306
      MYSQL_USER: isucari
      MYSQL_DBNAME: isucari
      MYSQL_PASS: isucari
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: "/app/isucari"
    working_dir: "/src/webapp/go"
    volumes:
      - "$PWD:/src"
    network_mode: "host"
